### ISSUE TITLE
Giving away multiple projects

### ISSUE THREAD

**Issue by roman01la** [clj-commons/wishlist#23]
Hello! I'd like to transfer multiple projects of mine to clj-commons.

- https://github.com/roman01la/citrus
- https://github.com/roman01la/cljss
- https://github.com/roman01la/zprint-clj

What should I do?

**Comment by slipset** [comment]
Cool! I've sent you an invite to cli-commons, so you should be able to transfer your repos.
WRT publishing on Clojars, I guess we need to rebrand the artefacts to `clj-commons/..` since they're published under your own org, and I imagine you don't want to give cli-commons access to publish to your org.

**Comment by roman01la** [comment]
Ok. Just transferred all of them into the org. Will update artifacts later.

**Comment by roman01la** [comment]
@slipset Done. Could you please publish citrus 3.2.2 and cljss 1.6.4?

**Comment by slipset** [comment]
Nice! Will do!

**Comment by slipset** [comment]
done
